version: "3.3"

services:
#  mysql:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_DATABASE: devop
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password123
#      MYSQL_ROOT_PASSWORD: password123
#    ports:
#      - '3306:3306'

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    logging:
      driver: "none"
    ports:
      - "5601:5601"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
    depends_on:
      - "zookeeper"

#  s1:
#    build: ./
#    restart: on-failure
#    ports:
#      - "8008:8008"
#    depends_on:
#      - mysql
#      - kafka
#      - elasticsearch
#    links:
#      - mysql
#      - kafka
#      - elasticsearch
#
#  s2:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - "8007:8007"
#    depends_on:
#      - kafka
#    links:
#      - mysql
#      - kafka
#      - s1