version: 2
jobs:
  setup-project-env:
    docker:
      - image: circleci/mysql:latest
        environment:
          MYSQL_DATABASE: devop
          MYSQL_USER: root
          MYSQL_PASSWORD: password123
          MYSQL_ROOT_PASSWORD: password123
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
        environment:
          xpack.security.enabled: false
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    working_directory: /go/src/github.com/cocoagaurav/devops
    steps:
      - checkout

  build&test:
    working_directory: /go/src/github.com/cocoagaurav/devops
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: building
          command: |
            dep ensure
            go build -o s1 /cmd/s1 && go build -o s2 /cmd/s2
      - run:
          name: service-start
          command: |
            ./s1 -logtostderr &
            ./s2 -logtostderr &
      - run:
          name: test run
          command: |
            go vet ./...
            go test -v ./...
workflows:
  version: 2
  testing-flow:
    jobs:
      - setup-project-env:
          filters:
            branches:
              only: master
      - build&test:
          requires:
            - setup-project-env
          filters:
            branches:
              only:
                - master



