apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: devop
        - name: MYSQL_ROOT_PASSWORD
          value: password123
        image: mysql
        name: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysqlx
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-volume
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mysql

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


