apiVersion: apps/v1
kind: Deployment
metadata:
  name: s1service
  labels:
    app: s1
spec:
  selector:
    matchLabels:
      app: s1
  template:
    metadata:
      labels:
        app: s1
    spec:
      containers:
        - name: service1
          image: gauravcococadocker/s1
          ports:
            - containerPort: 8008
          livenessProbe:
            httpGet:
              port: 8008
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8008
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 10


---

apiVersion: v1
kind: Service
metadata:
  name: s1
  labels:
    app : s1
spec:
  ports:
    - port: 80
      targetPort: 8008
      protocol: TCP
  type: NodePort
  selector:
    app: s1




