apiVersion: apps/v1
kind: Deployment
metadata:
  name: s2service
  labels:
    app: s2
spec:
  selector:
    matchLabels:
      app: s2
  template:
    metadata:
      labels:
        app: s2
    spec:
      containers:
        - name: service2
          image: gauravcococadocker/s2
          imagePullPolicy: Always
          ports:
            - containerPort: 8007

---

apiVersion: v1
kind: Service
metadata:
  name: s2
  labels:
    app : s2
spec:
  ports:
    - port: 80
      targetPort: 8007
      protocol: TCP
  type: NodePort
  selector:
    app: s2



